package use_case.chatbot;

import entity.Answer;

/**
 * Encapsulates the output data for the chatbot, including the generated answer.
 */
public class ChatBotOutputData {
    /** The answer generated by the chatbot */
    private final Answer answer;

    /**
     * Constructs a ChatBotOutputData object with the specified answer.
     *
     * @param answer The generated answer from the chatbot.
     */
    public ChatBotOutputData(Answer answer) {
        this.answer = answer;
    }

    /**
     * Retrieves the generated answer from the chatbot.
     *
     * @return The chatbot's answer.
     */
    public Answer getAnswer() {
        return answer;
    }
}
