package interface_adapter.chatbot;

import entity.Answer;

/**
 * Represents the state of the chatbot, including the generated answer.
 */
public class ChatBotState {
    /** The answer generated by the chatbot */
    private Answer answer;

    /**
     * Constructs a ChatBotState with the specified answer.
     *
     * @param answer The answer generated by the chatbot.
     */
    public ChatBotState(Answer answer) {
        this.answer = answer;
    }

    /**
     * Constructs an empty ChatBotState with no initial answer.
     */
    public ChatBotState() {
    }

    /**
     * Retrieves the answer generated by the chatbot.
     *
     * @return The chatbot's answer.
     */
    public Answer getAnswer() {
        return answer;
    }
}
